version: "3.8"

services:
  nextcoal-app:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  maps-expander:
    build: ./maps-expander
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3001/expand?url=https://maps.google.com",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: nextcoal-network
